pub struct Track {
    pub id: [u8; 16],
    pub name: String,
    pub artists: String,
    pub album: String,
    pub album_cover: Option<String>,
    pub release_date: Option<String>,
    pub duration: i32,
    pub explicit: bool,
    pub danceability: f32,
    pub acousticness: f32,
    pub energy: f32,
    pub instrumentalness: f32,
    pub key: i32,
    pub mode: i32,
    pub liveness: f32,
    pub loudness: f32,
    pub speechiness: f32,
    pub tempo: f32,
    pub valence: f32,
    pub time_signature: i32,
}
